### ISSUE TITLE
Linux version fails to start

### ISSUE THREAD

**Issue by alfrix** [zDEFz/c2-patch#2]
```
./Linux-32-Start cultris2.sh: línea 4: cd: demasiados argumentos
Cultris II 1.4c Community Patch 20/12/2021, Network 29
Fastl33t 120 0.1
OpenJDK 64-Bit Server VM warning: You have loaded library resources/libs/liblwjgl.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
java.lang.UnsatisfiedLinkError: resources/libs/liblwjgl.so: resources/libs/liblwjgl.so: clase ELF errónea: ELFCLASS32 (Possible cause: can't load IA 32 .so on a AMD 64 platform)
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:395)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:234)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:176)
        at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:322)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:291)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2427)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:848)
        at java.base/java.lang.System.loadLibrary(System.java:2015)
        at org.lwjgl.C.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at org.lwjgl.Sys.else(Unknown Source)
        at org.lwjgl.Sys.break(Unknown Source)
        at org.lwjgl.Sys.<clinit>(Unknown Source)
        at org.lwjgl.opengl.Display.<clinit>(Unknown Source)
        at JB-game-parameters.<clinit>(Unknown Source)
        at net.gewaltig.cultris.Cultris.break(Unknown Source)
        at net.gewaltig.cultris.Cultris.main(Unknown Source)
----------------------- Remaining sh.t in UpdateManager
java.lang.NoClassDefFoundError: Could not initialize class JB-game-parameters
        at sD-generate-crashreport.break(Unknown Source)
        at sD-generate-crashreport.else(Unknown Source)
        at Wc.windowClosed(Unknown Source)
        at java.desktop/java.awt.Window.processWindowEvent(Window.java:2088)
        at java.desktop/java.awt.Window.processEvent(Window.java:2044)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4991)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4823)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: /home/alfre/Escritorio/C2 AIO Linux/resources/libs/liblwjgl.so: /home/alfre/Escritorio/C2 AIO Linux/resources/libs/liblwjgl.so: clase ELF errónea: ELFCLASS32 (Possible cause: can't load IA 32 .so on a AMD 64 platform) [in thread "main"]
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:395)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:234)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:176)
        at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:322)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:291)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2427)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:848)
        at java.base/java.lang.System.loadLibrary(System.java:2015)
        at org.lwjgl.C.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at org.lwjgl.Sys.else(Unknown Source)
        at org.lwjgl.Sys.break(Unknown Source)
        at org.lwjgl.Sys.<clinit>(Unknown Source)
        at org.lwjgl.opengl.Display.<clinit>(Unknown Source)
        at JB-game-parameters.<clinit>(Unknown Source)
        at net.gewaltig.cultris.Cultris.break(Unknown Source)
        at net.gewaltig.cultris.Cultris.main(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.Sys
        at sD-generate-crashreport.break(Unknown Source)
        at sD-generate-crashreport.else(Unknown Source)
        at Wc.windowClosed(Unknown Source)
        at java.desktop/java.awt.Window.processWindowEvent(Window.java:2088)
        at java.desktop/java.awt.Window.processEvent(Window.java:2044)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4991)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4823)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Linux/resources/libs/liblwjgl.so: resources/libs/liblwjgl.so: clase ELF errónea: ELFCLASS32 (Possible cause: can't load IA 32 .so on a AMD 64 platform) [in thread "main"]
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:395)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:234)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:176)
        at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:322)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:291)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2427)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:848)
        at java.base/java.lang.System.loadLibrary(System.java:2015)
        at org.lwjgl.C.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at org.lwjgl.Sys.else(Unknown Source)
        at org.lwjgl.Sys.break(Unknown Source)
        at org.lwjgl.Sys.<clinit>(Unknown Source)
        at org.lwjgl.opengl.Display.<clinit>(Unknown Source)
        at JB-game-parameters.<clinit>(Unknown Source)
        at net.gewaltig.cultris.Cultris.break(Unknown Source)
        at net.gewaltig.cultris.Cultris.main(Unknown Source)
```

**Comment by zDEFz** [comment]
Supply with bellsoft jdk 17  https://bell-sw.com/pages/downloads/#/java-17-lts%20/%20current

tested working on 
# release file
```
IMPLEMENTOR="BellSoft"

JAVA_VERSION="17.0.1"

JAVA_VERSION_DATE="2021-10-19"

LIBC="gnu"

MODULES="java.base java.compiler java.datatransfer java.xml java.prefs java.desktop java.instrument java.logging java.management java.security.sasl java.naming java.rmi java.management.rmi java.net.http java.scripting java.security.jgss java.transaction.xa java.sql java.sql.rowset java.xml.crypto java.se java.smartcardio jdk.accessibility jdk.internal.jvmstat jdk.attach jdk.charsets jdk.compiler jdk.crypto.ec jdk.crypto.cryptoki jdk.dynalink jdk.internal.ed jdk.editpad jdk.hotspot.agent jdk.httpserver jdk.incubator.foreign jdk.incubator.vector jdk.internal.le jdk.internal.opt jdk.internal.vm.ci jdk.internal.vm.compiler jdk.internal.vm.compiler.management jdk.jartool jdk.javadoc jdk.jcmd jdk.management jdk.management.agent jdk.jconsole jdk.jdeps jdk.jdwp.agent jdk.jdi jdk.jfr jdk.jlink jdk.jpackage jdk.jshell jdk.jsobject jdk.jstatd jdk.localedata jdk.management.jfr jdk.naming.dns jdk.naming.rmi jdk.net jdk.nio.mapmode jdk.random jdk.sctp jdk.security.auth jdk.security.jgss jdk.unsupported jdk.unsupported.desktop jdk.xml.dom jdk.zipfs"

OS_ARCH="x86_64"

OS_NAME="Linux"

SOURCE=".:git:75240a5872a1+"
```

# Flow
```
def@def-VirtualBox:~$ cd /home/def/Downloads/
def@def-VirtualBox:~/Downloads$ sh '/home/def/Downloads/Linux-32-Start cultris2.sh' 
Cultris II 1.4c Community Patch 20/12/2021, Network 29
Fastl33t 120 0.1
LWJGL 2.8.5
OpenGL 3.1
Flux capacitor engaged! DeLorean went 3.386 forwards.
Update check: false false
```

# Linux-32-Start cultris2.sh
````
#!/bin/bash
export DIR=$(pwd)$DIR

cd $DIR
"./resources/jdk-17.0.1-lin/bin/java" -Djava.library.path="$DIR/resources/libs/" -jar "$DIR/cultris2.jar"
```

**Comment by zDEFz** [comment]
Bundled a new package.

Please try either one of them.

- Google Drive https://drive.google.com/file/d/18GKx8C5THz9H5vOs8W8YLM1F1hQmTV0Z/view?usp=sharing

- MEGA.NZ https://mega.nz/file/h8EyGLKJ#qRHEQKzS-BRavfxpCWS0f6DS9d_wh_CetC5QpBGqcJ0

**Comment by alfrix** [comment]
With belllsoft v17

> Cultris II 1.4c Community Patch 20/12/2021, Network 29
> Fastl33t 120 3.5
> LWJGL 2.8.5
> /usr/include/c++/11.1.0/array:188: std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](std::array<_Tp, _Nm>::size_type) [with _Tp = bool; long unsigned int _Nm = 4; std::array<_Tp, _Nm>::reference = bool&; std::array<_Tp, _Nm>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
> ./Linux-32-Start cultris2.sh: línea 5: 10277 Abortado

**Comment by zDEFz** [comment]
Working known: Ubuntu 20.04.3 LTS
Please specify the OS+OS version. You have been saying earlier, it's Manjaro. Want to reproduce it in my Virtual Machine order to find the solution.
It fails right where its supposed to load the OpenGL. 

Nonetheless, will try now with manjaro-xfce-21.2.1-220103-linux515.iso.

**Comment by alfrix** [comment]
i'm using the manjaro KDE, but should be different in this regard

i've tried openjdk 8 (works with the old patch)

but on this:
`Exception in thread "main" java.lang.UnsupportedClassVersionError: net/gewaltig/cultris/Cultris has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

i've tried openjdk11
`        java.lang.UnsupportedClassVersionError: net/gewaltig/cultris/Cultris has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 55.0`

then tried openjdk17
`Inconsistency detected by ld.so: dl-lookup.c: 105: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!`

**Comment by zDEFz** [comment]
The new version requires jdk of at least version 15.  
It was compiled with azul zulu 15.0.5 https://www.azul.com/downloads/

I cant provide the same functionality when using a SDK from approx 10 years ago.
The SDK is the oldest working on Windows,  macOS and on Linux.

The reason is the GUI that is provided. As the main process runs the GUI, it requires to be at least with jdk 15. 

booted the manjaro-xfce-21.2.1-220103-linux515.iso with proprietary drivers and heres a screenshot of it working.
Impressive that a boot alone was enough. Don't even need to install manjaro. A+ :)

![image](https://user-images.githubusercontent.com/24463722/149573721-13d2aad2-f89f-42d8-a3c8-c974b2a637e5.png)

**Comment by zDEFz** [comment]
https://drive.google.com/file/d/18GKx8C5THz9H5vOs8W8YLM1F1hQmTV0Z/view?usp=sharing was used.

**Comment by zDEFz** [comment]
Add:

1. Audio Pitch is altered for some reason on manjaro.
2. Text fields are slightly cut off. Should fix that by giving more height. 
3. On close 
![image](https://user-images.githubusercontent.com/24463722/149574574-e37adecd-4f31-4135-ace2-f9dcea96407b.png)

**Comment by zDEFz** [comment]
> but on this: `Exception in thread "main" java.lang.UnsupportedClassVersionError: net/gewaltig/cultris/Cultris has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

If I downgrade the class version to version 5, then the error would be that my constant X requires a newer version in order to work.

Without GUI, you require to load the value FPS each drawcall, from a textfile, as you cannot prevent it from being read more than once when you are using class version 5.

Then, this pseudocode would simply NOT work: 
```
public static int status=0;

public static int doSomething()
{
int tmp=0;

if(status==0)
{
//readMyFile returns an int
tmp=readMyFile();
status=1;
}

return;
}
```

**Comment by alfrix** [comment]
> https://drive.google.com/file/d/18GKx8C5THz9H5vOs8W8YLM1F1hQmTV0Z/view?usp=sharing
Nope, transparent windows then crash
![imagen](https://user-images.githubusercontent.com/1247237/149575947-bf30b424-17bb-4418-b18b-abea3b569b83.png)

I'm running very old hardware here, an old radeon with GL 3.1, maybe there is a new requirement?

**Comment by alfrix** [comment]
It does launch, but not from konsole
after giving it executable perms if you double click it it works, but  i cannot launch the way you showed 
![imagen](https://user-images.githubusercontent.com/1247237/149577450-2926a5f1-3ca7-42d9-9a8c-fda780d91b51.png)
weird

**Comment by zDEFz** [comment]
> It does launch, but not from konsole after giving it executable perms if you double click it it works, but i cannot launch the 

Hold on, can you explain what you did? I want to learn :)

Did you assign JAVA to your JAVA_HOME path, then `chmod +x *` and then simply double click the `.sh`?

**Comment by alfrix** [comment]
Just open the folder in the console do 
`chmod +x *.sh` (give executable permissions to the scripts)
then doble click the script

**Comment by alfrix** [comment]
the old version works doing this
![imagen](https://user-images.githubusercontent.com/1247237/149578514-168d238d-c858-4476-bee3-458dfd1c099f.png)

**Comment by zDEFz** [comment]
> Just open the folder in the console do `chmod +x *.sh` (give executable permissions to the scripts) then doble click the script

Okay. Should provide that information in the README, until we have a better solution.

About the different behavior: I think its really cause I spawn a new thread and have dependencies on functions that werent available on the old JDK.

**Comment by alfrix** [comment]
OMG it works from yakuake but not from konsole, wtf?
the issue was Konsole but why? idk not important, the patch is working now, thanks def
![imagen](https://user-images.githubusercontent.com/1247237/149578976-b25f7753-102e-4faa-bcfc-ccee67d6de89.png)
